-- AstroCommunity: import any community modules here
-- We import this file in `lazy_setup.lua` before the `plugins/` folder.
-- This guarantees that the specs are processed before any user plugins.

---@type LazySpec
return {
    "AstroNvim/astrocommunity",
    { import = "astrocommunity.colorscheme.everforest" },
    { import = "astrocommunity.completion.blink-cmp" },
    { import = "astrocommunity.completion.copilot-lua-cmp" },
    { import = "astrocommunity.debugging.nvim-dap-repl-highlights" },
    { import = "astrocommunity.debugging.nvim-dap-view" },
    { import = "astrocommunity.debugging.nvim-dap-virtual-text" },
    { import = "astrocommunity.diagnostics.trouble-nvim" },
    { import = "astrocommunity.editing-support.neogen" },
    { import = "astrocommunity.editing-support.treesj" },
    { import = "astrocommunity.file-explorer.oil-nvim" },
    { import = "astrocommunity.git.diffview-nvim" },
    { import = "astrocommunity.git.octo-nvim" },
    { import = "astrocommunity.motion.flit-nvim" },
    { import = "astrocommunity.motion.mini-move" },
    { import = "astrocommunity.motion.mini-surround" },
    { import = "astrocommunity.pack.docker" },
    { import = "astrocommunity.pack.go" },
    { import = "astrocommunity.pack.html-css" },
    { import = "astrocommunity.pack.lua" },
    { import = "astrocommunity.pack.nginx" },
    { import = "astrocommunity.pack.laravel" },
    { import = "astrocommunity.pack.php" },
    { import = "astrocommunity.pack.python" },
    { import = "astrocommunity.pack.sql" },
    { import = "astrocommunity.pack.typescript-all-in-one" },
    { import = "astrocommunity.pack.vue" },
    { import = "astrocommunity.pack.yaml" },
    { import = "astrocommunity.quickfix.nvim-bqf" },
    { import = "astrocommunity.recipes.astrolsp-no-insert-inlay-hints" },
    { import = "astrocommunity.recipes.auto-session-restore" },
    { import = "astrocommunity.recipes.disable-borders" },
    { import = "astrocommunity.recipes.disable-tabline" },
    { import = "astrocommunity.recipes.neo-tree-dark" },
    { import = "astrocommunity.recipes.picker-lsp-mappings" },
    { import = "astrocommunity.search.grug-far-nvim" },
    { import = "astrocommunity.test.neotest" },
    { import = "astrocommunity.utility.lua-json5" },
    { import = "astrocommunity.utility.noice-nvim" },
}
